# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58394371a02cdbc8208fd7bf4614167f324632ff991ce53cca02850eae69fe1a84ab65cca9de3d5e1d7ccacc088ee333a1c3984ad8f01c87e6ecd67de0cf0a34

test:
  secret_key_base: bcc77e491b276ca1746326235c869d5280cfc3ed78d4f474bd878ff659154dc926cec017be394c28c6163ed8fa6c851a3c8818174e14c85552c1f85943d02ebb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
